"""P1.1 auto-split tu db/repository.py (giu nguyen logic + comment goc).
Loi goi cheo module dung tham chieu _r_<module>.<ten> (tranh circular import).
KHONG sua tay truc tiep neu chua doc AGENTS; day la mot phan cua package db/repositories.
"""

from . import (
    _shared,
    chat,
    feedback,
    semantic_cache,
    document,
    document_pages,
    version,
    doc_metadata,
    lifecycle,
    bom,
    material,
    jobs,
    audit,
    qdrant,
    catalog,
    analytics,
    settings,
    access,
    glossary,
)
from ._shared import *  # noqa: F401,F403
from .chat import *  # noqa: F401,F403
from .feedback import *  # noqa: F401,F403
from .semantic_cache import *  # noqa: F401,F403
from .document import *  # noqa: F401,F403
from .document_pages import *  # noqa: F401,F403
from .version import *  # noqa: F401,F403
from .doc_metadata import *  # noqa: F401,F403
from .lifecycle import *  # noqa: F401,F403
from .bom import *  # noqa: F401,F403
from .material import *  # noqa: F401,F403
from .jobs import *  # noqa: F401,F403
from .audit import *  # noqa: F401,F403
from .qdrant import *  # noqa: F401,F403
from .catalog import *  # noqa: F401,F403
from .analytics import *  # noqa: F401,F403
from .settings import *  # noqa: F401,F403
from .access import *  # noqa: F401,F403
from .glossary import *  # noqa: F401,F403

__all__ = [
    'MAX_BOT_MSG_LEN',
    'MAX_USER_MSG_LEN',
    '_cap_len',
    '_sanitize_date',
    '_sanitize_int',
    '_sanitize_text',
    'normalize_base_code',
    'clear_chat_history',
    'get_all_sessions',
    'get_chat_history',
    'save_answer_sources',
    'save_chat_history',
    'QUALITY_HALF_LIFE_DAYS',
    'QUALITY_MIN_SAMPLE',
    'QUALITY_PRIOR',
    'QUALITY_SMOOTH_K',
    'ROLE_WEIGHTS',
    '_question_hash',
    '_role_weight',
    'add_regression_question',
    'cleanup_dangling_records',
    'ensure_regression_question',
    'find_golden_answer',
    'get_doc_quality_ranking',
    'get_latest_regression_batch',
    'get_regression_runs',
    'list_regression_questions',
    'mark_feedback_stale_for_doc',
    'normalize_question',
    'recompute_doc_quality_scores',
    'save_regression_run',
    'set_regression_question_active',
    'update_chat_feedback',
    'upsert_golden_answer',
    '_invalidate_semantic_cache',
    'sc_clear_all',
    'sc_delete',
    'sc_docs_all_current',
    'sc_get_candidates',
    'sc_put',
    'sc_record_hit',
    'sc_record_lookup',
    'sc_stats',
    '_get_or_create_doc',
    '_normalize_doc_type_label',
    '_prepare_metadata_params',
    'delete_document_completely',
    'find_current_docs',
    'get_doc',
    'get_document_departments',
    'get_document_info',
    'mark_document_ingest_failed',
    'set_document_departments',
    'update_document_classification',
    '_REINGEST_SNAPSHOT_TABLES',
    '_reingest_snapshots',
    '_snapshot_document_children',
    'clear_reingest_snapshot',
    'get_technical_attributes_for_rag',
    'reset_document_metadata',
    'restore_document_children',
    'save_document_attributes',
    'save_document_metadata',
    'save_document_page',
    'save_page_metadata',
    'save_technical_attributes',
    'verify_technical_attribute',
    'archive_document',
    'publish_as_new_variant',
    'publish_as_new_version',
    'publish_as_standalone',
    'reject_document',
    'rollback_to_version',
    'rollback_to_version_by_family',
    'update_document_full_metadata',
    '_COMMON_META_COLS',
    '_apply_upload_meta_to_doc',
    '_clean_meta_value',
    'get_common_metadata_for_rag',
    'get_document_attributes',
    'get_document_metadata',
    'set_document_attributes',
    'update_document_common_metadata',
    '_to_date',
    'classify_lifecycle',
    'get_lifecycle_overview',
    'mark_document_reviewed',
    'refresh_expired_status',
    'set_document_lifecycle',
    'normalize_material_name',
    'save_bom_records',
    'search_bom_by_code',
    '_refresh_material_cache',
    'add_material_synonym',
    'delete_material',
    'delete_material_synonym',
    'list_materials',
    'upsert_material',
    'cancel_job',
    'create_ingestion_job',
    'get_pending_job',
    'mark_job_failed',
    'mark_job_waiting_quota',
    'queue_eta_seconds',
    'requeue_job',
    'set_job_priority',
    'update_ingestion_job',
    'update_ingestion_report',
    'write_audit_log',
    '_get_qdrant_client',
    '_qdrant_client_singleton',
    'update_qdrant_metadata',
    '_CATALOG_CACHE_TTL',
    '_catalog_cache',
    '_catalog_cache_get',
    '_catalog_cache_invalidate',
    '_catalog_cache_put',
    '_departments_support_status',
    '_normalize_department_status',
    '_replace_department_token_list',
    '_resolve_site',
    '_split_csv_tokens',
    'archive_department',
    'get_department_summary',
    'get_user_sites',
    'list_known_departments',
    'list_known_sites',
    'reassign_department_data',
    'set_department_status',
    'set_user_clearance',
    'set_user_departments',
    'set_user_sites',
    'upsert_department',
    'upsert_site',
    '_NO_ANSWER_MARKERS',
    '_strip_accents_sql',
    '_tf',
    'count_docs_by_department',
    'dashboard_by_department',
    'get_observability',
    'get_usage_analytics',
    'save_rag_trace_summary',
    '_APP_SETTINGS_DEFAULTS',
    '_APP_SETTINGS_TTL',
    '_app_settings_cache',
    'get_all_app_settings',
    'get_app_setting',
    'get_app_setting_int',
    'set_app_setting',
    'count_pending_access_requests',
    'create_access_request',
    'get_grant_history',
    'get_user_access_requests',
    'list_access_requests',
    'list_users_with_access',
    'resolve_access_request',
    'revoke_user_clearance',
    'revoke_user_department',
    'delete_glossary_term',
    'get_active_glossary',
    'list_domain_glossary',
    'set_glossary_active',
    'upsert_glossary_term',
]
